// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3tJiB7tajKfUFTsQNyLmuWSuyo9KSRKE',
    appId: '1:160709417805:android:f561d4f2bdaede8ede7504',
    messagingSenderId: '160709417805',
    projectId: 'fir-test-b1efc',
    databaseURL: 'https://fir-test-b1efc.firebaseio.com',
    storageBucket: 'fir-test-b1efc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcNYsdwCKkaiV2dipazeDIreFBezVfVKw',
    appId: '1:160709417805:ios:fa4c2df97f245024de7504',
    messagingSenderId: '160709417805',
    projectId: 'fir-test-b1efc',
    databaseURL: 'https://fir-test-b1efc.firebaseio.com',
    storageBucket: 'fir-test-b1efc.appspot.com',
    androidClientId: '160709417805-759h1hs5kj2o1v4dctkorft7vulr12mm.apps.googleusercontent.com',
    iosClientId: '160709417805-lfh7toivb0ebcstsinhtgspc2bd9d34q.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailauth',
  );
}
